### PR TITLE
Added checks for bot token and webhook url length

### LINKED ISSUE #123: Passing an empty token or webhook url does not cause an error
### Description

If `SLACK_BOT_TOKEN` or `SLACK_WEBHOOK_URL` is set to an empty string, the action will succeed.
Is this intentional?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: v1.21.0

node version: 

OS version(s): ubuntu-22.04

#### Steps to reproduce:

1. Set `SLACK_BOT_TOKEN` or `SLACK_WEBHOOK_URL` to an empty string
2. Run workflow

#### Expected result:

Expect the action to fail.

#### Actual result:

The action will succeed.
Naturally, no message is sent.

#### Attachments:

Debugged in this repository: https://github.com/koki-develop/slack-github-action-debug

You can see that the action is not failing even though `SLACK_BOT_TOKEN` and `SLACK_WEBHOOK_URL` are set to empty characters or nonexistent secret.

Log: https://github.com/koki-develop/slack-github-action-debug/actions/runs/2991645944

> ```yaml
>       - uses: slackapi/slack-github-action@v1.21.0
>         env:
>           SLACK_WEBHOOK_URL: ""
>       - uses: slackapi/slack-github-action@v1.21.0
>         env:
>           SLACK_WEBHOOK_URL: ${{ secrets.NON_EXSISTENT_SECRET }}
> ```
> > https://github.com/koki-develop/slack-github-action-debug/blob/2fac0fd12078736e04359578a64b6e760faf86a6/.github/workflows/main.yml#L10-L15

### PR DESCRIPTION
**Pull request by koki-develop**
###  Summary

Fixed #123 

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Review by seratch — APPROVED** [review]
Thanks for the contribution! LGTM

**Comment by seratch** [comment]
The integration tests using env variables are failing. Need to investigate later

**Comment by koki-develop** [comment]
Hmmm...

PRs created from Forked repositories cannot see the secret.
As a result, empty strings are passed to `SLACK_BOT_TOKEN` and `SLACK_WEBHOOK_URL` on the integration test.
This PR added a check for empty string, which caused the integration test to fail 🤔 

screenshot

**Comment by seratch** [comment]
The test log console does not display the env variable values for better security.

@stevengill Do you have any thoughts on this? I think that env variables should be correctly set but am still unsure why the length validation that is added in this PR cause the test failures.

**Comment by koki-develop** [comment]
@seratch 

> The test log console does not display the env variable values for better security.

Yes, in the GitHub Actions log, the secret will appear as `***`, like:

log

The screenshot attached to the previous comment does not even show `***`.
This means that an empty value has been set.

**Comment by koki-develop** [comment]
As described in [this document](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow), secrets cannot be referenced from workflows triggered from a forked repository.

> Note: With the exception of `GITHUB_TOKEN`, secrets are not passed to the runner when a workflow is triggered from a forked repository.
> > https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow

For reference, if you want to refer to secrets from workflows triggered from a forked repository, you need to use the `pull_request_target` workflow trigger.
However, this may be dangerous from a security standpoint, so care should be taken.

> Due to the dangers inherent to automatic processing of PRs, GitHub’s standard `pull_request` workflow trigger by default prevents write permissions and secrets access to the target repository. However, in some scenarios such access is needed to properly process the PR. To this end the `pull_request_target` workflow trigger was introduced.
> > https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Review by stevengill — APPROVED** [review]

**Comment by Kurt-von-Laven** [comment]
This is a pretty bad experience for security-conscious users who aren't willing to use `pull_request_target` and receive PRs from forks. Before, there were simply no notifications from forks, which was a feature in our case. After, CI fails on any PR from a fork, which is a show stopper in our case because we use [Forking Renovate](https://github.com/apps/forking-renovate) for dependency bumps.

**Comment by sarisia** [comment]
Since this PR changes current behaviour which just `skips` for missing / invalid tokens, it would be helpful to consider this as breaking change and bump major version...

**Pull request merged**
