### PR TITLE
docs(readme): adjust whitespace in env assignment

### PR DESCRIPTION
**Pull request by paulo9mv**
###  Summary

This PR adjust a missing whitespace in README.
Now all env vars have the same pattern `${{ value }}` instead of `${{ value}}`.

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Comment by filmaj** [comment]
@paulo9mv our apologies, we've been experimenting w/ using a different deployment strategy for our CI and it seems like we still have some permission issues to resolve.

**Comment by paulo9mv** [comment]
No problems! Whenever it's ready feel free to merge :handshake:

**Comment by zimeg** [comment]
Hey @paulo9mv 👋  Could you rebase with the latest changes on `main`? We made a quick change to how CI checks are performed and I'm hoping things just work now 🙏

**Comment by paulo9mv** [comment]
> Hey @paulo9mv 👋 Could you rebase with the latest changes on `main`? We made a quick change to how CI checks are performed and I'm hoping things just work now 🙏

Done :heavy_check_mark:

**Review by zimeg — APPROVED** [review]
@paulo9mv appreciate ya sending in this fix and helping us figure out the tests! Everything is looking great :raised_hands:

**Pull request merged**
