### PR TITLE
Use method core.exportVariable instead of core.set-output

### PR DESCRIPTION
**Pull request by Nergie**
###  Summary

Fix https://github.com/slackapi/slack-github-action/issues/141

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Review by seratch — APPROVED** [review]
Looks good to me. Using core.exportVariable looks the right way to go https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-creating-an-annotation-for-an-error

**Comment by flaxel** [comment]
You don't need to change the method. Currently you write to `GITHUB_ENV` but the previous implementation wrote to `GITHUB_OUTPUT`. So it's only necessary to [bump the action dependency](https://github.com/actions/toolkit/pull/1178).

**Comment by seratch** [comment]
@flaxel Thanks for sharing this and this is great to hear! We can upgrade the version instead. If @Nergie is still interested in revising this PR, we will wait for it. Otherwise, I will come up with a new PR, which just upgrades the module.

**Comment by Nergie** [comment]
Thank @flaxel and @seratch. We don't need to bump the dependencies or change the method to export variables.
[@actions/core 1.10.0 ](https://github.com/slackapi/slack-github-action/blob/0591a83d97c714275147191f3660dde09458554e/package.json#L33) fixes the issue.  See [release notes](https://github.com/actions/toolkit/blob/main/packages/core/RELEASES.md).
I'll close this PR and the issue https://github.com/slackapi/slack-github-action/issues/141

**Pull request closed without merging**
