### PR TITLE
Add Missing Quote

### PR DESCRIPTION
**Pull request by ChunkLightTuna**
###  Summary

Add Missing Quote. Also the values key on line 45 does not appear to be valid, but I'm new to GH actions and possibly missing something.

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Comment by seratch** [comment]
Hi @ChunkLightTuna, thanks for submitting this pull request! 

The change looks great to me. Would you mind signing our CLA? (check the above bot message) Without having it, we are unable to merge your contribution 🙇

**Comment by seratch** [comment]
Hi @ChunkLightTuna, can you check my above comment?

**Review by srajiang — APPROVED** [review]
Looks good to merge.

**Review by seratch — APPROVED** [review]
Thanks for signing the CLA! LGTM again

**Pull request merged**
