### PR TITLE
feat: Support thread_ts parameter to post the new message as a thread

### LINKED ISSUE #187: Support thread_ts for threaded updates to a single topic
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [x] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

I would like the ability to gather updates from a long build+deploy process into a single thread. I'd love to use this (or a similar) pre-built action to accomplish this, but I don't see any support (input parameter?) for `thread_ts`. I know the Slack API supports that functionality; is it possible to extend this GitHub Action to leverage that feature?

### PR DESCRIPTION
**Pull request by ArnaudRinquin**
Closes #187

###  Summary

Describe the goal of this PR. Mention any related Issue numbers.

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Comment by WilliamBergamin** [comment]
Thanks for the contribution @ArnaudRinquin 💯 

Before I move forward with this would you mind testing out what happens if the `thread_ts` field is passed in the payload?

Based on the behavior from [this line](https://github.com/slackapi/slack-github-action/blob/53b162f7f5bedbf55515caebaee839322b18fb28/src/slack-send.js#L86) it seems like the spread operator should support `thread_ts` being placed in the `payload` argument 

```yml
- name: Send GitHub trigger payload to Slack Workflow Builder
  id: slack
  uses: slackapi/slack-github-action@v1.26.0
  with:
    channel-id: 'SLACK_CHANNEL_ID' # ID of Slack Channel you want to post to
    payload: |
      {
        "blocks": [
          { "type": "divider" },
          {
            "type": "image",
            "title": {
              "type": "plain_text",
              "text": "Slack Slack Slack",
              "emoji": true
            },
            "image_url": "https://media.makeameme.org/created/a-slack-this.jpg",
            "alt_text": "marg"
          },
          {
            "type": "actions",
            "elements": [
              {
                "type": "button",
                "text": {
                  "type": "plain_text",
                  "text": "${{ github.sha }}"
                },
                "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }
            ]
          }
        ],
        "thread_ts": "TIMESTAMP_OF_A_MESSAGE"
      }
  env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```

**Comment by ArnaudRinquin** [comment]
@WilliamBergamin I've added 2 test cases ensuring payload provided `thread_ts` is still used + overrides input passed `thread-ts` (I'm not sure which should be used in priority but seems better this way).

**Comment by WilliamBergamin** [comment]
@ArnaudRinquin these are awesome changes 💯 but implementing the simplest solution for this problem should create a more maintainable project

It would be awesome if this PR could include the `unit tests` that ensures payload provided `thread_ts` is valid and documentation on how to use payload provided `thread_ts`. With this we will be able to update and close #187

**Comment by ArnaudRinquin** [comment]
@WilliamBergamin 

> ensures payload provided thread_ts is valid 

I'd be happy to validate the thread_ts value but I can't find any spec on the expected shape. Even in [official doc](https://api.slack.com/interactivity/handling) the type looks like it can be a simple string. I'll had more tests if you can provide me some hints on how to validate.

CleanShot 2024-04-26 at 18 16 14@2x

I've updated README.md example of specifying thread_ts from payload.

**Comment by fleytman** [comment]
[WilliamBergamin](https://github.com/WilliamBergamin), what is blocking this pr at the moment?

**Comment by WilliamBergamin** [comment]
Closing in favor of #309

**Pull request closed without merging**
