### PR TITLE
Improve the readability of example payloads

### PR DESCRIPTION
**Pull request by seratch**
###  Summary

This pull request improves the readability of the payload examples in README. Also, I've renamed the example directory names (again) to better align with README.

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Review by misscoded — APPROVED** [review]
Definite improvement to the readability of the payloads. Thanks for taking the time to do this!

**Comment by seratch** [comment]
Perhaps, merging this PR will cause conflicts with other PRs from the community. I'm fine to hold off this one until we merge the others that came before this PR.

**Review by srajiang — APPROVED** [review]

**Review by filmaj — APPROVED** [review]
💯

**Comment by stevengill** [comment]
Probably okay to revisit this PR now

**Pull request merged**
